# Generated by Django 4.1.5 on 2023-01-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0002_post_date_post_descricao_post_link_post_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nome',
        ),
        migrations.AddField(
            model_name='post',
            name='seu_nome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
