# Generated by Django 4.1.5 on 2023-01-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0003_remove_post_nome_post_seu_nome_alter_post_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='seu_nome',
        ),
        migrations.AddField(
            model_name='post',
            name='nome',
            field=models.CharField(max_length=20, null=True, verbose_name='Nome do autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(max_length=300, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=30, null=True, verbose_name='Titulo da postagem'),
        ),
    ]
