# Generated by Django 4.1.5 on 2023-01-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0004_remove_post_seu_nome_post_nome_alter_post_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_perfil',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_tumb',
            field=models.TextField(null=True),
        ),
    ]
