# Generated by Django 4.1.5 on 2023-01-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0005_post_link_perfil_post_link_tumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(null=True, verbose_name='Link para direcionar o usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link_perfil',
            field=models.TextField(null=True, verbose_name='Link da Foto do perfil'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link_tumb',
            field=models.TextField(null=True, verbose_name='Link pro Wallpaper dessa postagem'),
        ),
    ]
