# Generated by Django 4.1.5 on 2023-01-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0006_alter_post_link_alter_post_link_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link_perfil',
        ),
    ]
